import localFont from "next/font/local";
import "./globals.css";
import Navbar, { NavFoot, NavGroup, NavHead, NavLink } from "@/Component/Navbar";
import ScrollArea from "@/Component/ScrollArea";
import Header from "@/uicomponents/Header";
import PageNavbar from "@/uicomponents/PageNavbar";
import { metadata as defaultMetadata } from './layout'; // Import default

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});
 


// src/app/layout.js
export const metadata = ({ children, ...props }) => {
    // Provide default values if no page-specific data is passed
    const pageTitle = props.pageTitle || "uiZ | Home"; 
    const pageDescription = props.pageDescription || "Generated by create next app";

    return {
        title: pageTitle,
        description: pageDescription,
        // ... other metadata properties
    };
};

// ... rest of your layout component




export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased moderscroller`} >
				<div className='h-screen bg-black flex flex-col gap-2 md:p-4 p-3'>
					<PageNavbar />
					{children}
				</div>
			</body>
		</html>
	);
}
